"""Visualization and export helpers for reconstructed surfaces."""

from __future__ import annotations

import json
import os
from typing import Dict, Optional

import numpy as np

try:
    import cv2
except ImportError:  # pragma: no cover
    cv2 = None

import matplotlib.pyplot as plt

from .image_codec import cv2_write_image_any_path
from .pointcloud import PointCloudData, save_point_cloud


def save_reconstruction_outputs(
    result,
    output_dir: str,
    pixels_per_mm: float,
    point_cloud: Optional[PointCloudData] = None,
    save_point_cloud_file: bool = True,
    heatmap_cmap: str = "turbo",
) -> Dict[str, str]:
    """Save the main artifacts generated by the reconstruction pipeline."""

    os.makedirs(output_dir, exist_ok=True)
    paths = {}

    full_focus_path = os.path.join(output_dir, "full_focus.png")
    write_rgb_image(full_focus_path, result.full_focus_rgb)
    paths["full_focus_png"] = full_focus_path

    depth_npy_path = os.path.join(output_dir, "depth_map_mm.npy")
    np.save(depth_npy_path, result.depth_map_mm.astype(np.float32))
    paths["depth_npy"] = depth_npy_path

    raw_depth_npy_path = os.path.join(output_dir, "depth_map_raw_mm.npy")
    np.save(raw_depth_npy_path, result.raw_depth_map_mm.astype(np.float32))
    paths["raw_depth_npy"] = raw_depth_npy_path

    valid_mask_path = os.path.join(output_dir, "valid_mask.npy")
    np.save(valid_mask_path, result.valid_mask.astype(bool))
    paths["valid_mask_npy"] = valid_mask_path

    depth_tiff_path = os.path.join(output_dir, "depth_map_um16.tif")
    write_depth_tiff16(depth_tiff_path, result.raw_depth_map_mm, result.valid_mask)
    paths["depth_tiff16"] = depth_tiff_path

    heatmap_path = os.path.join(output_dir, "depth_heatmap.png")
    save_depth_heatmap(
        depth_map_mm=result.raw_depth_map_mm,
        valid_mask=result.valid_mask,
        output_path=heatmap_path,
        cmap_name=heatmap_cmap,
        detail_mode="absolute",
    )
    paths["depth_heatmap_png"] = heatmap_path

    heatmap_detail_path = os.path.join(output_dir, "depth_heatmap_detail.png")
    save_depth_heatmap(
        depth_map_mm=result.raw_depth_map_mm,
        valid_mask=result.valid_mask,
        output_path=heatmap_detail_path,
        cmap_name=heatmap_cmap,
        detail_mode="detail",
    )
    paths["depth_heatmap_detail_png"] = heatmap_detail_path

    frame_scores_csv = os.path.join(output_dir, "frame_focus_scores.csv")
    save_frame_scores_csv(frame_scores_csv, result.z_positions_mm, result.frame_focus_scores, result.file_paths)
    paths["frame_scores_csv"] = frame_scores_csv

    frame_scores_png = os.path.join(output_dir, "frame_focus_scores.png")
    save_focus_curve(frame_scores_png, result.z_positions_mm, result.frame_focus_scores)
    paths["frame_scores_png"] = frame_scores_png

    if point_cloud is not None and save_point_cloud_file:
        ply_path = os.path.join(output_dir, "surface_point_cloud.ply")
        save_point_cloud(ply_path, point_cloud)
        paths["point_cloud_ply"] = ply_path

        csv_path = os.path.join(output_dir, "surface_point_cloud.csv")
        save_point_cloud(csv_path, point_cloud)
        paths["point_cloud_csv"] = csv_path

    manifest_path = os.path.join(output_dir, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as handle:
        json.dump(
            {
                "generator": "zstack_3d",
                "output_dir": output_dir,
                "input_files": result.file_paths,
                "z_positions_mm": [float(value) for value in result.z_positions_mm],
                "pixels_per_mm": float(pixels_per_mm),
                "focus_volume_shape": list(result.focus_volume_shape),
                "alignment_offsets_px": [[float(dx), float(dy)] for dx, dy in result.alignment_offsets_px],
                "reconstruction_config": result.reconstruction_config,
                "depth_map_note": "depth_map_mm.npy is smoothed output; depth_map_raw_mm.npy is recommended for fine metrology and line-profile measurement",
                "artifacts": {key: os.path.basename(value) for key, value in paths.items()},
            },
            handle,
            ensure_ascii=False,
            indent=2,
        )
    paths["manifest_json"] = manifest_path
    return paths


def write_rgb_image(output_path: str, rgb_image: np.ndarray) -> None:
    rgb_u8 = np.clip(rgb_image, 0, 255).astype(np.uint8)
    if cv2 is not None:
        if cv2_write_image_any_path(output_path, rgb_u8[:, :, ::-1]):
            return
    plt.imsave(output_path, rgb_u8)


def write_depth_tiff16(output_path: str, depth_map_mm: np.ndarray, valid_mask: np.ndarray) -> None:
    depth = np.asarray(depth_map_mm, dtype=np.float32)
    valid = np.asarray(valid_mask, dtype=bool) & np.isfinite(depth)
    if not np.any(valid):
        raise ValueError("Depth map does not contain valid values")

    relative_um = np.zeros(depth.shape, dtype=np.float32)
    relative_um[valid] = (depth[valid] - float(np.nanmin(depth[valid]))) * 1000.0
    depth_u16 = np.clip(relative_um, 0, 65535).astype(np.uint16)

    if cv2 is not None:
        if cv2_write_image_any_path(output_path, depth_u16):
            return
    plt.imsave(output_path, depth_u16, cmap="gray")


def save_depth_heatmap(
    depth_map_mm: np.ndarray,
    valid_mask: np.ndarray,
    output_path: str,
    cmap_name: str = "turbo",
    detail_mode: str = "absolute",
) -> None:
    depth = np.asarray(depth_map_mm, dtype=np.float32)
    valid = np.asarray(valid_mask, dtype=bool) & np.isfinite(depth)

    fig, ax = plt.subplots(figsize=(8, 6), dpi=160)
    if np.any(valid):
        masked = np.ma.array(depth, mask=~valid)
        valid_values = depth[valid]
        if detail_mode == "detail":
            vmin = float(np.percentile(valid_values, 5.0))
            vmax = float(np.percentile(valid_values, 95.0))
            if vmax <= vmin + 1e-9:
                vmin = float(np.min(valid_values))
                vmax = float(np.max(valid_values))
            title = "Depth Heatmap (Detail Enhanced)"
        else:
            vmin = float(np.min(valid_values))
            vmax = float(np.max(valid_values))
            title = "Depth Heatmap"
        image = ax.imshow(masked, cmap=cmap_name, vmin=vmin, vmax=vmax)
        cbar = fig.colorbar(image, ax=ax, fraction=0.046, pad=0.04)
        cbar.set_label("Height (mm)")
    else:
        ax.imshow(np.zeros(depth.shape, dtype=np.float32), cmap=cmap_name)
        title = "Depth Heatmap"
    ax.set_title(title)
    ax.set_xlabel("X (pixel)")
    ax.set_ylabel("Y (pixel)")
    fig.tight_layout()
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def save_focus_curve(
    output_path: str,
    z_positions_mm: np.ndarray,
    frame_focus_scores: np.ndarray,
) -> None:
    fig, ax = plt.subplots(figsize=(7.2, 4.2), dpi=160)
    ax.plot(z_positions_mm, frame_focus_scores, marker="o", linewidth=1.8)
    ax.set_xlabel("Z position (mm)")
    ax.set_ylabel("Mean focus score")
    ax.set_title("Frame-wise Focus Curve")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def save_frame_scores_csv(
    output_path: str,
    z_positions_mm: np.ndarray,
    frame_focus_scores: np.ndarray,
    file_paths,
) -> None:
    import csv

    with open(output_path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["frame_index", "file_name", "z_mm", "focus_score"])
        for index, (z_mm, score, path) in enumerate(zip(z_positions_mm, frame_focus_scores, file_paths)):
            writer.writerow([index, os.path.basename(path), float(z_mm), float(score)])
